---
fullname: A Formal Theory of Games of Incomplete Information Based on Belief Functions
shortname: belgames
organization: pPomCo
community: false
branch: main
action: true
nix: false
coqdoc: false
dune: false
# doi: TODO

synopsis: >-
  BelGames: A Formal Theory of Games of Incomplete Information Based
  on Belief Functions in the Coq Proof Assistant

description: |-
  We extend Bayesian games to the theory of belief functions. We
  obtain a more expressive class of games we refer to as BelGames. It
  makes it possible to better capture human behaviors with respect to
  lack of information.
  Next, we prove an extended version of the so-called
  Howson--Rosenthal's theorem, showing that BelGames can be turned
  into games of complete information, i.e., without any uncertainty.

publications:
  - pub_url: "https://ut3-toulouseinp.hal.science/hal-03782650"
    pub_title: "Bel-Games: A Formal Theory of Games of Incomplete Information Based on Belief Functions in the Coq Proof Assistant (2022)"
#   pub_doi: TODO

authors:
- name: Pierre Pomeret-Coquot
  initial: true
- name: Erik Martin-Dorel
  initial: true
- name: Hélène Fargier
  initial: true

maintainers:
- name: Pierre Pomeret-Coquot
  nickname: pPomCo
- name: Erik Martin-Dorel
  nickname: erikmd

opam-file-maintainer: erik.martin-dorel@irit.fr

opam-file-version: dev

license:
  fullname: MIT
  identifier: MIT

supported_coq_versions:
  text: 8.14 or later (use releases for other Coq versions)
  opam: '{(>= "8.14" & < "8.17~")}'

dependencies:
- opam:
    name: coq-mathcomp-algebra
    version: '{(>= "1.13" & < "1.16~")}'
  description: |-
    [MathComp](https://math-comp.github.io) 1.13.0 or later (`algebra` suffices)

tested_coq_opam_versions:
- version: '1.15.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '1.15.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: '1.15.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.14.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.15'
  repo: 'mathcomp/mathcomp'

# ci_cron_schedule: '20 4 * * *'

namespace: BelGames

keywords:
- name: games of incomplete information
- name: belief functions theory
- name: mathcomp/ssreflect

# categories:
# - name: Computer Science/Formal Languages Theory and Automata

# documentation: |-
#   ## HTML Documentation
# 
#   To generate HTML documentation, run `make coqdoc` and point your browser at `docs/coqdoc/toc.html`.
# 
#   See also the pregenerated HTML documentation for the [latest release](https://ppomco.github.io/coq-belgames-csl2023/docs/latest/coqdoc/toc.html).
# 
#   ## File Contents
# 
#   * `file.v`: TODO
---
